In [1]:
import numpy as np

# --------
# -- Q1 --
# --------
# A. Create the array: with out explicitly typing it in.
a = np.arange(1,16).reshape(3,5)
b = a.transpose()
b

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [2]:
#     Now create a new array containing only its 2nd and 4th rows.
c = b[(1,3),:]
c

array([[ 2,  7, 12],
       [ 4,  9, 14]])

In [3]:
# B. Create a 2d array with 1 on the border and 0 on the inside:
#     Do this using array slice notation to let it work for an arbitrary-sized array
r = 4
c = 4
d = np.zeros((r,c))
f = d.copy()
f[:,0]  = 1
f[0,:]  = 1
f[-1,:] = 1
f[:,-1] = 1
f

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [4]:



# --------
# -- Q2 --
# --------
'''
 Here we will read in columns of numbers from a file and create a histogram, using NumPy routines. 
 Make sure you have the data file "sample.txt" in the same directory as this notebook. 
 You download it from https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt 
 (and use python to download a file!)
     - Use np.loadtxt() to read this file in.
     - Next, use np.histogram() to create a histogram array. The output returns both the count and an array of edges.
     - Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.
'''

import requests

url = 'https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt'
r = requests.get(url, allow_redirects=True)

open('sample.txt', 'wb').write(r.content)

data = np.loadtxt("sample.txt")
print(data.shape)

(100, 2)


In [5]:
count,edges = np.histogram(data[:,0],weights=data[:,1])
count

array([  6.06970305, -52.2011722 ,   0.70141063, -47.80477715,
       -22.94861378,  19.33283482,  84.58174822,  91.31342333,
        42.07282212,  -1.86282183])

In [6]:
edges

array([ 0. ,  9.9, 19.8, 29.7, 39.6, 49.5, 59.4, 69.3, 79.2, 89.1, 99. ])

In [7]:
for i in range(len(count)):
    mean = 0.5*(edges[i]+edges[i+1])
    print("bin center: ", mean, "\tcount: ",count[i])

bin center:  4.95 	count:  6.069703047865552
bin center:  14.850000000000001 	count:  -52.201172195233326
bin center:  24.75 	count:  0.7014106349144356
bin center:  34.650000000000006 	count:  -47.804777150191036
bin center:  44.55 	count:  -22.94861377762616
bin center:  54.45 	count:  19.33283482185784
bin center:  64.35 	count:  84.58174821855998
bin center:  74.25 	count:  91.3134233340054
bin center:  84.15 	count:  42.07282211700763
bin center:  94.05000000000001 	count:  -1.8628218331290585


In [8]:


# --------
# -- Q3 --
# --------
'''
Write a function to calculate the standard deviation for an input array, a:
    - First compute the average of the elements in a to define a-mean
    - Next compute the sum over the squares of 
    - Then divide the sum by the number of elements in the array
    - Finally take the square root (you can use np.sqrt())
Test your function on a random array, and compare to the built-in np.std(). Check the runtime as well.
'''

def standard_dev(array):
    diff = np.sum( ( array - np.mean(array) )**2 )
    N = array.size
    std_dev = np.sqrt(diff/N)
    return std_dev
    

In [9]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
import time

t0 = time.time()
std = standard_dev(a)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))
std

time elapsed: 0.0003178119659423828 s


4.320493798938574

In [11]:
t2 = time.time()
np.std(a)
t3 = time.time()
print("time elapsed: {} s".format(t3-t2))

time elapsed: 0.0005519390106201172 s


In [12]:
print("Standard deviation : my function time is {} numpy function time.".format((t1-t0)/(t3-t2)))

Standard deviation : my function time is 0.5758099352051835 numpy function time.


In [13]:


# --------
# -- Q4 --
# --------

'''
Boostrapping is a prominent statistical tecnique to estimate errors when you're stuck and don't know what else to do: 
https://erikjanvankesteren.nl/blog/2018-03-01-baron-bootstrap.html

    - Generate a 1D array (say from a Gaussian, but then add some outliers for fun). 
    - Compute the bootstrapped 95% confidence intervals for the mean of that array 
        (i.e., 
            . resample the elements of an array with replacement N times, 
            . compute the mean of each sample
            . compute percentiles over the means).
'''




"\nBoostrapping is a prominent statistical tecnique to estimate errors when you're stuck and don't know what else to do: \nhttps://erikjanvankesteren.nl/blog/2018-03-01-baron-bootstrap.html\n\n    - Generate a 1D array (say from a Gaussian, but then add some outliers for fun). \n    - Compute the bootstrapped 95% confidence intervals for the mean of that array \n        (i.e., \n            . resample the elements of an array with replacement N times, \n            . compute the mean of each sample\n            . compute percentiles over the means).\n"

In [15]:
import numpy as np
data = np.random.normal(loc=0, scale=1, size=100)  # Gaussian distribution
outliers = np.random.normal(loc=10, scale=5, size=10)  # Outliers
data_with_outliers = np.concatenate((data, outliers))

# Bootstrapping
N = 1000  # Number of bootstrap samples
bs_means = []
for _ in range(N):
    bs_sample = np.random.choice(data_with_outliers, size=len(data_with_outliers), replace=True)
    bs_means.append(np.mean(bs_sample))

# Compute confidence intervals
CL = np.percentile(bs_means, [2.5, 97.5])

In [16]:
print(CL)

[0.20602939 1.20401305]
